export { default as Home } from './Home'
export { default as Login } from './Login'
export { default as NotFound } from './NotFound'
export { default as Admin } from './Admin'
export { default as AddShop } from './Admin/AddShop'
